apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-test-automation-api
  labels:
    app: cicd-test-automation-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-test-automation-api
  template:
    metadata:
      labels:
        app: cicd-test-automation-api
    spec:
      containers:
        - name: cicd-test-automation-api
          image: ghcr.io/sakshipatel29/cicd-test-automation-framework:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
