apiVersion: v1
kind: Service
metadata:
  name: cicd-test-automation-service
spec:
  type: NodePort
  selector:
    app: cicd-test-automation-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
